# Generated by Django 3.1.2 on 2021-01-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6'), ('S7', 'S7'), ('S8', 'S8'), ('S9', 'S9'), ('S10', 'S10'), ('S11', 'S2'), ('S12', 'S2'), ('ED', 'ED')], max_length=30)),
                ('defect', models.CharField(choices=[('XS', 'Excess'), ('WL', 'Waterleak'), ('PH', 'Pin Hole'), ('F', 'Flick'), ('ED R', 'ED run'), ('ED B', 'ED Blister'), ('NS', 'No Spat'), ('OF', 'Off Location'), ('MC', 'Missing Clip'), ('PA', 'Poor Application'), ('NB', 'No Brush'), ('G', 'Gap'), ('MAS', 'Mastic'), ('BB', 'Body Bound')], max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('period', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th')], max_length=30)),
            ],
        ),
    ]
