# Generated by Django 3.1.2 on 2021-02-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputcs', '0002_sheet_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='location',
            field=models.CharField(default='front door', max_length=50),
            preserve_default=False,
        ),
    ]
