# Generated by Django 3.1.2 on 2021-02-15 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputcs', '0003_sheet_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='author',
        ),
    ]
