# Generated by Django 3.1.5 on 2021-02-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputcs', '0004_remove_sheet_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='imagecoor',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
