# Generated by Django 3.1.2 on 2021-02-16 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputcs', '0005_sheet_imagecoor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='imagecoor',
        ),
    ]
