# Generated by Django 3.1.2 on 2021-02-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputcs', '0006_remove_sheet_imagecoor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='coordinates',
            field=models.JSONField(default='none'),
            preserve_default=False,
        ),
    ]
