# Generated by Django 3.1.2 on 2021-02-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputcs', '0007_sheet_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='coordinates',
            field=models.CharField(max_length=30),
        ),
    ]
