# Generated by Django 3.1.2 on 2021-02-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputcs', '0008_auto_20210217_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='sheet',
            name='coorx',
            field=models.CharField(default='2', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheet',
            name='coory',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
    ]
