# Generated by Django 3.1.2 on 2021-02-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputcs', '0010_auto_20210217_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='coorx',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='coory',
            field=models.IntegerField(),
        ),
    ]
