# Generated by Django 3.1.2 on 2021-02-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputcs', '0015_ajaximage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='coorx',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='coory',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
