# Generated by Django 3.1.2 on 2021-03-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputcs', '0016_auto_20210222_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='location',
        ),
        migrations.AlterField(
            model_name='ajaximage',
            name='image_coord',
            field=models.FloatField(),
        ),
    ]
