# Generated by Django 3.1.2 on 2021-03-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputcs', '0017_auto_20210307_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='period',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=30),
        ),
    ]
