# Generated by Django 3.1.5 on 2021-03-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputcs', '0018_auto_20210307_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
